// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

dotenv.config();
console.log("Loaded environment variables:", {
  DATABASE_URL: process.env.DATABASE_URL ? "Loaded" : "Not Loaded",
  NODE_ENV: process.env.NODE_ENV || "Not Set",
});
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
